# Create 3d clone of the scene

In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

In [32]:
points_3d = np.array([[463, 925,   0],
                      [412, 925,   0],
                      [412, 599,   0],
                      [463, 925, 120],
                      [412, 925, 120],
                      [412, 599, 120],
                      [338, 919,   0],
                      [291, 923,   0],
                      [338, 919, 120],
                      [291, 923, 120]])

In [33]:
points_2d = np.array([[1932, 1314],
                      [1556, 1332],
                      [1412,  524],
                      [2071,  772],
                      [1619,  764],
                      [1432,  257],
                      [ 942, 1355],
                      [ 546, 1336],
                      [ 760,  777],
                      [ 407,  803]])

In [34]:
n = points_2d.shape[0]
u = points_2d[:,0]
v = points_2d[:,1]
X = points_3d[:,0]
Y = points_3d[:,1]
Z = points_3d[:,2]
A = np.zeros((2*n, 12))

In [35]:
for i in range(n):
    A[2*i,:] = [X[1], Y[i], Z[i], 1, 0, 0, 0, 0, -u[i]*X[i], -u[i]*Y[i], -u[i]*Z[i], -u[i]]
    A[2*i+1,:] = [0, 0, 0, 0, X[i], Y[i], Z[i], 1, -v[i]*X[i], -v[i]*Y[i], -v[i]*Z[i], -v[i]]

In [36]:
b = points_2d.reshape((2*n,1))

## Calculation 1

In [42]:
U, S, V = np.linalg.svd(A)

In [43]:
M = V[:, -1].reshape((3, 4))

In [44]:
M

array([[ 1.02201225e-03, -7.51760115e-04, -3.40209225e-04,
        -1.19861184e-02],
       [ 2.23541987e-01, -8.99477212e-01,  1.07035353e-01,
        -2.99838861e-01],
       [ 3.48518092e-02, -1.95565765e-01,  1.95097252e-03,
        -4.99013195e-14]])

In [52]:
points_3d_h = np.concatenate((points_3d, np.ones((n,1))), axis=1)
points_2d_h = np.dot(M, points_3d_h.T)
points_2d_h = points_2d_h / points_2d_h[2,:]
print(points_2d_h.T)
print(points_2d)

[[1.42127814e-03 4.42345056e+00 1.00000000e+00]
 [1.71908388e-03 4.44469607e+00 1.00000000e+00]
 [4.01044897e-04 4.34876311e+00 1.00000000e+00]
 [1.67143553e-03 4.35167767e+00 1.00000000e+00]
 [1.96698687e-03 4.37372018e+00 1.00000000e+00]
 [8.00056760e-04 4.23344347e+00 1.00000000e+00]
 [2.12815782e-03 4.47385802e+00 1.00000000e+00]
 [2.39752508e-03 4.49308912e+00 1.00000000e+00]
 [2.37455410e-03 4.40351771e+00 1.00000000e+00]
 [2.64078678e-03 4.42377593e+00 1.00000000e+00]]
[[1932 1314]
 [1556 1332]
 [1412  524]
 [2071  772]
 [1619  764]
 [1432  257]
 [ 942 1355]
 [ 546 1336]
 [ 760  777]
 [ 407  803]]


[[1.42127814e-03 4.42345056e+00 1.00000000e+00]
 [1.71908388e-03 4.44469607e+00 1.00000000e+00]
 [4.01044897e-04 4.34876311e+00 1.00000000e+00]
 [1.67143553e-03 4.35167767e+00 1.00000000e+00]
 [1.96698687e-03 4.37372018e+00 1.00000000e+00]
 [8.00056760e-04 4.23344347e+00 1.00000000e+00]
 [2.12815782e-03 4.47385802e+00 1.00000000e+00]
 [2.39752508e-03 4.49308912e+00 1.00000000e+00]
 [2.37455410e-03 4.40351771e+00 1.00000000e+00]
 [2.64078678e-03 4.42377593e+00 1.00000000e+00]] [[1932 1314]
 [1556 1332]
 [1412  524]
 [2071  772]
 [1619  764]
 [1432  257]
 [ 942 1355]
 [ 546 1336]
 [ 760  777]
 [ 407  803]]


## Calculation 2

In [51]:
#camera_matrix, dist_coeffs, rvecs, tvecs = cv2.calibrateCamera(points_3d, points_2d, [2592, 1944], None, None)

error: OpenCV(4.6.0) /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/calib3d/src/calibration.cpp:3350: error: (-210:Unsupported format or combination of formats) objectPoints should contain vector of vectors of points of type Point3f in function 'collectCalibrationData'


## Calculation 3

In [54]:
res = np.linalg.lstsq(A, b, rcond=None)

In [55]:
m = res[0]

In [56]:
M = m.reshape((3,4))

In [57]:
print(M)

[[-2.50338987e-14  1.00204133e-14  4.20981374e-15  4.16954256e-14]
 [-4.89013646e-15  2.19053124e-15  3.17821275e-15 -3.69946293e-13]
 [-1.08733303e-17  7.46208022e-18  1.56979828e-17 -1.00000000e+00]]


In [58]:
points_3d_h = np.concatenate((points_3d, np.ones((n,1))), axis=1)
points_2d_h = np.dot(M, points_3d_h.T)
points_2d_h = points_2d_h / points_2d_h[2,:]
print(points_2d_h.T)
print(points_2d)

[[ 2.28011736e-12  6.07838079e-13  1.00000000e+00]
 [ 1.00338853e-12  3.58441120e-13  1.00000000e+00]
 [ 4.27004327e-12  1.07255430e-12  1.00000000e+00]
 [ 1.77493971e-12  2.26452550e-13  1.00000000e+00]
 [ 4.98210878e-13 -2.29444098e-14  1.00000000e+00]
 [ 3.76486562e-12  6.91168774e-13  1.00000000e+00]
 [-7.88997498e-13  9.71420915e-15  1.00000000e+00]
 [-2.00567239e-12 -2.28884330e-13  1.00000000e+00]
 [-1.29417515e-12 -3.71671321e-13  1.00000000e+00]
 [-2.51085004e-12 -6.10269859e-13  1.00000000e+00]]
[[1932 1314]
 [1556 1332]
 [1412  524]
 [2071  772]
 [1619  764]
 [1432  257]
 [ 942 1355]
 [ 546 1336]
 [ 760  777]
 [ 407  803]]
